#TODO eliminare i commenti
#TODO eliminare directory VaultService
#TODO eliminare dockerfile in mysqlserivce
#TODO variabili d'ambiente per mysl-password e token-vault

services:
  mysql-db:
    image: mysql:9.2.0
    container_name: Mysql_Service
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "InStore_db"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_OPTS: "--lower_case_table_names=1"
    volumes:
      - mysql-data:/var/lib/mysql
    #      - ./MySqlService/persistence:/var/lib/mysql
    command: --lower_case_table_names=1

  keycloak:
    build: ./KeycloakService
    container_name: keycloak-manager
    environment:
#      KC_HOSTNAME: http://keycloak-manager:8080
#      KC_HTTP_HOST: keycloak-manager
      KC_HOSTNAME_DEBUG: true
      KC_HTTP_ENABLED: true
    ports:
      - "8090:8080"
    volumes:
      - ./KeycloakService/data:/opt/keycloak/data

  vault:
    image: hashicorp/vault:1.18.4
    container_name: vault-service
    restart: "no"
    ports:
      - '8200:8200'
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl

  vault-init:
    container_name: vault-init
    image: hashicorp/vault:1.18.4
    restart: "no"
    environment:
      VAULT_ADDR: "http://vault-service:8200"
    volumes:
      - ./vault/unseal-vault.sh:/vault/unseal-vault.sh
    entrypoint: sh -c "sleep 3 && /vault/unseal-vault.sh"
    cap_add:
      - IPC_LOCK
    depends_on:
      - vault

  application-core:
    build:
      context: ./ApplicationCore
      dockerfile: Dockerfile
    container_name: ApplicationCore_Service
    #image: bise97/application-core
    restart: "no"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
    depends_on:
      - mysql-db
      - vault-init
      - keycloak
    ports:
      - "8081:8080"

  nginx:
    build:
      context: ./NgnixService
      dockerfile: Dockerfile
    container_name: Nginx_Manager
    #image: bise97/instore-nginx
    restart: "no"
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./NgnixService/nginx.conf:/etc/nginx/nginx.conf
   #   - letsencrypt:/etc/letsencrypt  # Volume per i certificati
   #   - certbot-data:/var/www/certbot   # Volume per la sfida ACME
    depends_on:
      - application-core

#  debug:
#    image: weibeld/ubuntu-networking
#    stdin_open: true
#    tty: true
#    networks:
#     - app-network

#  certbot:
#    image: certbot/certbot:v1.23.0
#    container_name: certbot
#    restart: "no"
#    volumes:
#      #- ./certbot/conf:/etc/letsencrypt:rw
#      #- ./certbot/www:/var/www/certbot:rw
#      - certbot-data:/var/www/certbot
#      - letsencrypt:/etc/letsencrypt
#    networks:
#      - app-network
#    depends_on:
#      - nginx
#    command:
#      - renew
#      #- certonly
#      #- --webroot
#      #- -w
#      #- /var/www/certbot
#      #- --email=paolorusso3196@gmail.com
#      #- --agree-tos
#      #- --no-eff-email
#      #- -d
#      #- instore.puntoitstore.it

# Definizione dei volumi per la persistenza dei dati
volumes:
  mysql-data:
    name: instore-mysql
#  certbot-data:
#  letsencrypt: