#TODO eliminare i commenti

###########################################
#
# To test the app locally with nginx and keycloak integrated together
# you have to set up "local DNS rules" to resolve the domain names.
#
# In Windows you can modify the file "C:\Windows\System32\drivers\etc\hosts", adding the lines:
#   127.0.0.1 instore.puntoitstore.it
#   127.0.0.1 login.instore.puntoitstore.it
# You are bonding these domains names to the local IP address.
#
# To test in remote, you have to set DNS records to bond the domains instore.puntoitstore.it
# and login.instore.puntoitstore.it to the public IP address of your web server.
#
###########################################

services:
  mysql-db:
    image: mysql:9.2.0
    container_name: mysql.instore.puntoitstore.it
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "InStore_db"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_OPTS: "--lower_case_table_names=1"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-certs:/etc/mysql/certs:ro
    command:
      - --lower_case_table_names=1
      - --require-secure-transport=ON
      - --ssl-cert=/etc/mysql/certs/fullchain.pem
      - --ssl-key=/etc/mysql/certs/privkey.pem

#  ##########################
#
#   3 users:
#    - user1   ->  CLIENTE
#    - seller1 ->  RIVENDITORE
#    - admin1  ->  ADMIN
#  username and password are the same.
#
#  ########################
  keycloak:
    build: keycloak/keycloak:26.1
    ##TODO cercare di non accedere come root, modificando solo i permessi di lettura dei certificati
    user: "0:0"
    container_name: login.instore.puntoitstore.it
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      # remember to modify Root URL in instore-client settings by keycloak UI
      KC_HOSTNAME: ${KC_EXT_URL}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_DEBUG: "true"
      KC_HTTP_ENABLED: "false"
      KC_HTTPS_ENABLED: "true"
      KC_HTTPS_PORT: "8443"
      KC_HTTPS_CERTIFICATE_FILE: "/etc/keycloak/certs/fullchain.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/etc/keycloak/certs/privkey.pem"
    ports:
      - "8090:8443"
    volumes:
      - ./KeycloakService/data:/opt/keycloak/data
      - keycloak-certs:/etc/keycloak/certs:ro
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --log="console,file"

  keycloak2604:
    image: keycloak/keycloak:26.0.4
    user: "0:0"
    container_name: login.instore.puntoitstore.it
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      # remember to modify Root URL in instore-client settings by keycloak UI
      KC_HOSTNAME: ${KC_EXT_URL}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_DEBUG: true
      KC_HTTP_ENABLED: false
      KC_HTTPS_ENABLED: true
      KC_HTTPS_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /etc/keycloak/certs/fullchain.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/keycloak/certs/privkey.pem
    ports:
      - "8090:8443"
    volumes:
      - ./KeycloakService/data2604:/opt/keycloak/data
      - keycloak-certs:/etc/keycloak/certs:ro
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --log="console,file"
  #    entrypoint: /opt/keycloak/bin/kc.sh import --file /opt/keycloak/data/realms.cfg

  vault:
    image: hashicorp/vault:1.18.4
    container_name: vault.instore.puntoitstore.it
    restart: "no"
    ports:
      - '8200:8200'
    volumes:
      - ./VaultService/config:/vault/config
      - ./VaultService/policies:/vault/policies
      - ./VaultService/data:/vault/data
      - ./VaultService/logs:/vault/logs
      - vault-certs:/vault/certs:ro

    environment:
      VAULT_ADDR: "https://0.0.0.0:8200"
      VAULT_API_ADDR: "https://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl

  vault-init:
    container_name: vault-init
    image: hashicorp/vault:1.18.4
    restart: "no"
    environment:
      VAULT_ADDR: ${VAULT_URL}
    volumes:
      - ./VaultService/unseal-vault.sh:/vault/unseal-vault.sh
    entrypoint: sh -c "sleep 3 && /vault/unseal-vault.sh"
    cap_add:
      - IPC_LOCK
    depends_on:
      - vault

  application-core:
    image: openjdk:17-jdk-slim
    container_name: instore.puntoitstore.it
    restart: "no"
    environment:
      APPLICATION_URL: ${APP_EXT_URL}
      KEYCLOAK_URL: ${KC_INT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_URL: ${VAULT_URL}
      MYSQL_URL: ${MYSQL_URL}
    depends_on:
      - vault-init
    ports:
      - "8081:8080"
    volumes:
      - ./ApplicationCore/target/${JAR_FILE}:/target/app.jar
      - application-core-certs:/app/certs:ro
    entrypoint: java -jar /target/app.jar

  nginx:
    build:
      context: ./NgnixService
      dockerfile: Dockerfile
    container_name: nginx
    #image: bise97/instore-nginx
    restart: "no"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./NgnixService/nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt  # Volume per i certificati
      #- certbot-data:/var/www/certbot   # Volume per la sfida ACME
    depends_on:
      - application-core

#  debug:
#    image: weibeld/ubuntu-networking
#    stdin_open: true
#    tty: true
#    networks:
#     - app-network

#  certbot:
#    image: certbot/certbot:v1.23.0
#    container_name: certbot
#    restart: "no"
#    volumes:
#      - certbot-data:/var/www/certbot
#      - letsencrypt:/etc/letsencrypt
#    depends_on:
#      - nginx
#    command:
#      - renew
      #- certonly
      #- --webroot
      #- -w
      #- /var/www/certbot
      #- --email=paolorusso3196@gmail.com
      #- --agree-tos
      #- --no-eff-email
      #- -d
      #- instore.puntoitstore.it

volumes:
  mysql-data:
    name: instore-mysql

  certbot-data:
  letsencrypt:

  mysql-certs:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /var/lib/docker/volumes/instore_letsencrypt/_data/live/mysql.instore.puntoitstore.it

  vault-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/volumes/instore_letsencrypt/_data/live/vault.instore.puntoitstore.it

  application-core-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/volumes/instore_letsencrypt/_data/live/instore.puntoitstore.it

  keycloak-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/volumes/instore_letsencrypt/_data/live/login.instore.puntoitstore.it

