version: '3.8'
#TODO eliminare i commenti
#TODO eliminare directory VaultService
#TODO eliminare dockerfile in mysqlserivce
#TODO variabili d'ambiente per mysl-password e token-vault

services:
  mysql-db:
    image: mysql:9.2.0
    container_name: Mysql_Service
    restart: "no"
    networks:
      - app-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "InStore_db"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_OPTS: "--lower_case_table_names=1"
    volumes:
      - mysql-data:/var/lib/mysql
#      - ./MySqlService/persistence:/var/lib/mysql
    command: --lower_case_table_names=1

  # Servizio Keycloak per la gestione dell'autenticazione
#  keycloak:
#    build: ./KeycloakService                        # path of dockerfile
#    container_name: Keycloak_Manager
#    ports:
#      - "8090:8090"                                 # Mappa la porta 8090 per l'accesso a Keycloak
#    volumes:
#      - ./KeycloakService/data:/opt/keycloak/data
#    networks:
#      - app-network

  vault:
    image: hashicorp/vault:1.18.4
    container_name: vault-service
    restart: "no"
    ports:
      - '8200:8200'
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    networks:
      - app-network
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl


  vault-init:
    container_name: vault-init
    image: hashicorp/vault:1.18.4
    restart: "no"
    environment:
      VAULT_ADDR: "http://vault-service:8200"
    volumes:
      - ./vault/unseal-vault.sh:/vault/unseal-vault.sh
    entrypoint: sh -c "sleep 3 && /vault/unseal-vault.sh"
    networks:
      - app-network
    cap_add:
      - IPC_LOCK
    depends_on:
      - vault

  application-core:
    build:
      context: ./ApplicationCore
      dockerfile: Dockerfile
    container_name: ApplicationCore_Service
    image: bise97/application-core
    restart: "no"
    environment:
      VAULT_TOKEN: "hvs.6cW8zKkrzeQA17xZAQvu0GeS"
    networks:
      - app-network
    depends_on:
      - mysql-db
      - vault-init
#      - keycloak
    ports:
      - "8081:8080"

  nginx:
    build:
      context: ./NgnixService  # Percorso del Dockerfile per Nginx
      dockerfile: Dockerfile  # Nome del Dockerfile
    container_name: Nginx_Manager  # Nome del contenitore Nginx
    #image: bise97/instore-nginx
    restart: "no"
    ports:
      - "80:80"  # Mappa la porta 80 per il traffico HTTP
    volumes:
      - ./NgnixService/nginx.conf:/etc/nginx/nginx.conf  # Configurazione personalizzata di Nginx
    networks:
      - app-network
    depends_on:
      - application-core

#  certbot:
#    image: certbot/certbot:latest
#    container_name: certbot
#    restart: "no"
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    networks:
#      - app-network
#    depends_on:
#      - nginx

# Definizione delle reti utilizzate dai vari servizi
networks:
  app-network:
    external: true  # Rete esterna già esistente per i contenitori

# Definizione dei volumi per la persistenza dei dati
volumes:
  mysql-data:
    name: instore-mysql

