POST http://localhost:8081/api/clienti/aggiungi_standard
Content-Type: application/x-www-form-urlencoded

username = cliente2 &
email = cliente2@example.com &
password = password000 &
numCell = 76848683 &
nome = Mario &
cognome = Rossi &
numeroCarta = 34524325456 &
dataScadenza = 2027-12-31 &
nomeIntestatario = Gino &
cognomeIntestatario = Verdi &
cvc = 333
