POST http://instore.puntoitstore.it/api/clienti/aggiungi_standard
Cookie: JSESSIONID=B8DC5F0B6AA5F49CE33860C7EE338F90
Content-Type: application/x-www-form-urlencoded

username = cliente1 &
email = cliente1@example.com &
numCell = 3465433 &
nome = Mario &
cognome = Rossi &
numeroCarta = 58768989 &
dataScadenza = 2027-12-31 &
nomeIntestatario = Mario &
cognomeIntestatario = Rossi &
cvc = 333
