POST https://instore.puntoitstore.it/api/cliente-registration
Cookie: JSESSIONID=959B070157132B29E2A3A27EF2E0A37B
Content-Type: application/x-www-form-urlencoded

nome=Mario&
cognome=Rossi&
numeroCarta=58768989&
dataScadenza=2027-12-31&
nomeIntestatario=Mario&
cognomeIntestatario=Rossi&
cvc=333
