-- Inserisci dati nella tabella RIVENDITORE (che include campi da Utente)
INSERT INTO rivenditore (username, email, password, num_cell, nome_societa, partita_iva, iban, stato_rivenditore) VALUES
                                                                                                                      ('rivenditore1', 'alpha@example.com', 'password1', '1234567890', 'Società Alpha', '12345678901', 'IT60X0542811101000000123456', 'ABILITATO'),
                                                                                                                      ('rivenditore2', 'beta@example.com', 'password2', '0987654321', 'Società Beta', '98765432109', 'IT60Y0542811102000000654321', 'INATTESA'),
                                                                                                                      ('rivenditore3', 'gamma@example.com', 'password3', '098000000', 'Società Gamma', '98765430000', 'IT60Y0542811102000000000000', 'DISABILITATO');
-- Inserisci dati nella tabella PRODOTTO, associandoli ai Rivenditori
INSERT INTO prodotto (nome_prodotto, descrizione, prezzo, taglia, immagine, path_immagine, quantita_totale, rivenditore_username) VALUES
                                                                                                                                ('Maglietta', 'Maglietta in cotone 100%', 19.99, 'M', 'maglietta.jpg', '/images/maglietta.jpg', 50, 'rivenditore1'),
                                                                                                                                ('Pantaloni', 'Pantaloni eleganti in lino', 49.99, 'L', 'pantaloni.jpg', '/images/pantaloni.jpg', 30, 'rivenditore1'),
                                                                                                                                ('Scarpe', 'Scarpe sportive', 59.99, '42', 'scarpe.jpg', '/images/scarpe.jpg', 20, 'rivenditore1');