### TEST con rotta API application Core
### Inserisci un nuovo prodotto
POST http://localhost:8080/api/rivenditori/rivenditore2/insprodotti
Content-Type: application/json

{
  "nomeProdotto": "pippo",
  "descrizione": "pluto",
  "prezzo": 20.99,
  "taglia": "L",
  "immagine": "pantaloni.jpg",
  "pathImmagine": "/images/pantalonie.jpg",
  "quantitaTotale": 30
}
### ListaProdotti inseriti
####
GET http://localhost:8080/api/rivenditori/rivenditore1/listaprodotti
Accept: application/json
### TEST con rotta API Ngnix

### Inserisci un nuovo prodotto per il rivenditore "rivenditore2"
POST http://localhost/api/rivenditori/rivenditore1/insprodotti
Content-Type: application/json

{
  "nomeProdotto": "pippo",
  "descrizione": "pluto",
  "prezzo": 20.99,
  "taglia": "L",
  "immagine": "pantaloni.jpg",
  "pathImmagine": "/images/pantalonie.jpg",
  "quantitaTotale": 30
}

### Ottieni la lista prodotti del rivenditore "rivenditore1"
GET http://localhost/api/rivenditori/rivenditore1/listaprodotti
Accept: application/json
