### Inserisci un nuovo prodotto
### Inserimento di un prodotto per un rivenditore
### Inserimento Prodotto per il Rivenditore 1
POST http://localhost:8081/api/rivenditori/rivenditore2/insprodotti
Content-Type: application/json

{
  "nomeProdotto": "T-Shirt basic",
  "descrizione": "T-Shirt semplice 100% cotone, colore bianco.",
  "prezzo": 10.99,
  "taglia": "M",
  "pathImmagine": "/images/t-shirt.jpg",
  "quantitaTotale": 25
}
### ListaProdotti inseriti
####
GET http://localhost:8081/api/rivenditori/rivenditore1/listaprodotti
Accept: application/json
#####

