# Definisce i servizi del progetto
services:
  # Nome del servizio Keycloak
  keycloak:
    # Usa il contesto di build corrente (dove si trova il Dockerfile)
    build: .
    # Assegna un nome specifico al container
    container_name: Keycloak_Manager
    # Definisce le variabili d'ambiente per configurare Keycloak
    environment:
      # Nome utente e password per l'amministrazione di Keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # Mappa la porta 8080 del container sulla porta 8090 dell'host
    ports:
      - "8090:8080"
    # Collega il container alla rete specificata
    networks:
      - app-network

# Configura le reti Docker
networks:
  # Usa una rete esterna, se già esistente
  app-network:
    external: true

