# Usa l'immagine di MySQL come base
FROM mysql:9.2.0
#TODO eliminare questo docker file e impostare le variabili d'ambiente direttamente nel docker-compose
# Imposta variabili d'ambiente per MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=InStore_db


