name: Deploy to DigitalOcean

on:
  push:
    branches:
      - biagio

env:
  DOCKER_COMPOSE_VERSION: "1.29.2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push
          
      - name: Deploy to DigitalOcean
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            rm -r InStore/
            git clone https://github.com/PaoloR96/InStore.git -b biagio
            cd ~/InStore/vault
            chmod +x unseal-vault.sh
            cd ..
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker-compose up -d
          EOF
