name: Deploy to DigitalOcean

on:
  push:
    branches:
      - biagio

env:
  DOCKER_COMPOSE_VERSION: "1.29.2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
          docker --version
          docker-compose --version

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose build

      # Run Trivy scan for each image
      - name: Trivy scan - mysql-db
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'mysql-db'
          format: 'sarif'
          output: 'trivy-results-mysql-db.sarif'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF - mysql-db
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-mysql-db.sarif'

      - name: Trivy scan - keycloak2604
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'keycloak2604'
          format: 'sarif'
          output: 'trivy-results-keycloak2604.sarif'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF - keycloak2604
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-keycloak2604.sarif'

      - name: Trivy scan - vault
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'vault'
          format: 'sarif'
          output: 'trivy-results-vault.sarif'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF - vault
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-vault.sarif'

      - name: Trivy scan - application-core
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'application-core'
          format: 'sarif'
          output: 'trivy-results-application-core.sarif'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF - application-core
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-application-core.sarif'

      - name: Trivy scan - nginx
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'nginx'
          format: 'sarif'
          output: 'trivy-results-nginx.sarif'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF - nginx
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-nginx.sarif'

      - name: Deploy to DigitalOcean
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            rm -r InStore/
            git clone https://github.com/PaoloR96/InStore.git -b biagio
            chown -R vaultuser:vaultgroup InStore/VaultService
            cd InStore/VaultService
            chmod +x unseal-vault.sh
            cd ..
            docker-compose down
            docker-compose build   
            cd ApplicationCore
            mvn clean package -DskipTests
            cd ..
            docker-compose up -d
            sleep 10
            docker-compose up -d
          EOF
