name: Docker Build & Security Scan

on:
  push:
    branches:
      - biagio

jobs:
  docker-security-scan:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write  # Necessario per caricare i report SARIF su GitHub Security

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
          docker --version
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker images
        run: |
          docker build -t instore/mysql-db ./MysqlService
          docker build -t instore/vault ./VaultService
          docker build -t instore/nginx ./NginxService
          docker build -t instore/application-core ./ApplicationCore

      - name: Trivy scan - mysql-db
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: instore/mysql-db
          format: sarif
          output: trivy-results-mysql-db.sarif

      - name: Trivy scan - vault
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: instore/vault
          format: sarif
          output: trivy-results-vault.sarif

      - name: Trivy scan - nginx
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: instore/nginx
          format: sarif
          output: trivy-results-nginx.sarif

      - name: Trivy scan - application-core (optional)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: instore/application-core
          format: sarif
          output: trivy-results-appcore.sarif

      - name: Upload Trivy SARIF results - mysql-db
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results-mysql-db.sarif

      - name: Upload Trivy SARIF results - vault
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results-vault.sarif

      - name: Upload Trivy SARIF results - nginx
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results-nginx.sarif

      - name: Upload Trivy SARIF results - application-core
        if: ${{ exists('trivy-results-appcore.sarif') }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results-appcore.sarif

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            rm -r InStore/
            git clone https://github.com/PaoloR96/InStore.git -b biagio
            chown -R vaultuser:vaultgroup InStore/VaultService
            cd InStore/VaultService
            chmod +x unseal-vault.sh
            cd ..
            docker-compose down
            docker-compose build   
            cd ApplicationCore
            mvn clean package -DskipTests
            cd ..
            docker-compose up -d
            sleep 10
            docker-compose up -d
          EOF