services:
  nginx:
    build: .
    container_name: Nginx_manager
    ports:
      # Porta HTTP
      - "80:80"
      # Porta HTTPS
      # - "443:443"
    volumes:
      # Monta la configurazione Nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Monta la cartella dei certificati
      # - ./cert:/etc/nginx/cert
    networks:
      - app-network

networks:
  app-network:
    external: true
